import { Submission } from "./types";

export const submissions: Submission[] = [
  { id: "SM-1001", title: "Post-Quantum Key Exchange for Low-Power IoT Devices", authors: "A. Raza, S. Fatima", abstract: "We propose a lattice-based key exchange optimized for constrained microcontrollers, reducing handshake overhead by 41% while preserving forward secrecy under standard assumptions.", status: "Under Review", submittedAt: "2026-07-02T09:15:00Z" },
  { id: "SM-1002", title: "Provenance Tracking in Federated Research Datasets", authors: "M. Khan", abstract: "A cryptographic provenance layer that binds dataset revisions to verifiable author identities across institutional boundaries without a central authority.", status: "Cleared", submittedAt: "2026-07-04T14:30:00Z" },
  { id: "SM-1003", title: "Detecting Paper-Mill Signatures with Graph Neural Networks", authors: "H. Ahmed, R. Iqbal", abstract: "We train a GNN on co-authorship and citation graphs to flag coordinated inauthentic submissions, achieving 0.92 AUC on a held-out set.", status: "Draft", submittedAt: "2026-07-06T11:00:00Z" },
  { id: "SM-1004", title: "Zero-Knowledge Proofs for Anonymous Peer Review", authors: "T. Malik", abstract: "A protocol letting reviewers prove domain expertise without revealing identity, using zk-SNARKs over a credential commitment.", status: "Under Review", submittedAt: "2026-07-08T08:45:00Z" },
  { id: "SM-1005", title: "Reproducibility Seals via Content-Addressed Storage", authors: "N. Sheikh, U. Farooq", abstract: "Binding published results to immutable IPFS hashes so that any later edit is detectable, improving reproducibility auditing.", status: "Rejected", submittedAt: "2026-07-09T16:20:00Z" },
  { id: "SM-1006", title: "Latency-Aware Scheduling for Edge Inference", authors: "K. Bhatti", abstract: "A scheduler that co-locates model shards to meet tail-latency targets on heterogeneous edge clusters.", status: "Cleared", submittedAt: "2026-07-11T10:05:00Z" },
  { id: "SM-1007", title: "A Formal Model of Desk-Rejection Criteria", authors: "L. Nawaz, F. Zaidi", abstract: "We formalize editorial screening rules as a decision procedure, enabling authors to self-check before submission.", status: "Under Review", submittedAt: "2026-07-13T13:10:00Z" },
  { id: "SM-1008", title: "Homomorphic Aggregation of Survey Responses", authors: "S. Qureshi", abstract: "Computing aggregate statistics over encrypted survey data to preserve respondent privacy in longitudinal studies.", status: "Draft", submittedAt: "2026-07-15T09:50:00Z" },
  { id: "SM-1009", title: "Watermarking LLM-Generated Review Text", authors: "A. Siddiqui, M. Tariq", abstract: "A statistical watermark that survives light paraphrasing, helping editors detect AI-authored referee reports.", status: "Cleared", submittedAt: "2026-07-17T15:35:00Z" },
  { id: "SM-1010", title: "Distributed Timestamping for Submission Priority", authors: "R. Aslam", abstract: "Using a threshold-signed log to establish tamper-evident submission ordering across mirrored servers.", status: "Under Review", submittedAt: "2026-07-19T12:25:00Z" },
  { id: "SM-1011", title: "Bias Auditing in Automated Screening Pipelines", authors: "Z. Hussain, D. Kamal", abstract: "An auditing framework that surfaces disparate desk-rejection rates across author demographics.", status: "Rejected", submittedAt: "2026-07-21T08:00:00Z" },
  { id: "SM-1012", title: "Compact Merkle Proofs for Citation Integrity", authors: "Y. Butt", abstract: "Reducing proof size for verifying that a citation list has not been altered post-acceptance.", status: "Draft", submittedAt: "2026-07-23T17:40:00Z" },
  { id: "SM-1013", title: "Secure Multi-Party Plagiarism Comparison", authors: "I. Chishti, P. Anand", abstract: "Two venues compare submissions for overlap without revealing full manuscripts, using private set intersection.", status: "Cleared", submittedAt: "2026-07-25T11:15:00Z" },
  { id: "SM-1014", title: "On-Device Redaction of Sensitive Methods Sections", authors: "G. Mir", abstract: "A client-side tool that redacts identifying methodology details before double-blind submission.", status: "Under Review", submittedAt: "2026-07-27T14:05:00Z" },
  { id: "SM-1015", title: "Verifiable Retraction Notices on an Append-Only Log", authors: "E. Farhan, V. Rao", abstract: "Ensuring retractions cannot be silently removed by publishing them to a tamper-evident append-only ledger.", status: "Draft", submittedAt: "2026-07-29T09:30:00Z" },
];